# SpawnRelay client installer for client "{{.ClientName}}" (Windows)
# Generated by {{.AdminURL}} (server version {{.Version}})
#
# Run from an elevated PowerShell prompt:
#   irm{{if .SkipCert}} -SkipCertificateCheck{{end}} '{{.AdminURL}}/install/client.ps1?token={{.Token}}' | iex
$ErrorActionPreference = 'Stop'

$Server      = '{{.Server}}'
$Token       = '{{.Token}}'
$Fingerprint = '{{.Fingerprint}}'
$AdminUrl    = '{{.AdminURL}}'
$SkipCert    = ${{if .SkipCert}}true{{else}}false{{end}}

$InstallDir = Join-Path $env:ProgramFiles 'SpawnRelay'
$Exe        = Join-Path $InstallDir 'spawnrelay.exe'
$EnvFile    = Join-Path $InstallDir 'client.env'
$TaskName   = 'SpawnRelayClient'

function Log($m) { Write-Host "[spawnrelay] $m" -ForegroundColor Cyan }

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { throw 'Please run this installer from an elevated (Administrator) PowerShell prompt.' }

$arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } elseif ([Environment]::Is64BitOperatingSystem) { 'amd64' } else { '386' }
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

# Previous versions: stop and remove the old task, end any client process
# still running so the binary can be replaced, and remove leftovers.
if (schtasks /Query /TN $TaskName 2>$null) {
  Log "stopping scheduled task '$TaskName' from the previous version"
  schtasks /End /TN $TaskName 2>$null | Out-Null
  schtasks /Delete /F /TN $TaskName 2>$null | Out-Null
}
$running = Get-CimInstance Win32_Process -Filter "Name = 'spawnrelay.exe'" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -match '\sclient(\s|$)' }
foreach ($p in $running) {
  Log "stopping spawnrelay client process (pid $($p.ProcessId))"
  Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue
}
if ($running) { Start-Sleep -Seconds 2 }
foreach ($leftover in @("$Exe.old", "$Exe.new")) {
  if (Test-Path $leftover) { Log "removing leftover $leftover"; Remove-Item -Force -ErrorAction SilentlyContinue $leftover }
}

Log "downloading spawnrelay for windows/$arch from $AdminUrl"
$url = "$AdminUrl/dl/spawnrelay_windows_$arch.exe"
if ($PSVersionTable.PSVersion.Major -ge 7) {
  if ($SkipCert) { Invoke-WebRequest -SkipCertificateCheck -Uri $url -OutFile $Exe } else { Invoke-WebRequest -Uri $url -OutFile $Exe }
} else {
  if ($SkipCert) { [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true } }
  [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
  Invoke-WebRequest -Uri $url -OutFile $Exe
}

@"
# SpawnRelay client configuration (generated $((Get-Date).ToUniversalTime().ToString('s'))Z)
SPAWNRELAY_SERVER=$Server
SPAWNRELAY_TOKEN=$Token
SPAWNRELAY_FINGERPRINT=$Fingerprint
# Accept updates pushed from the relay's management interface (0 to refuse)
SPAWNRELAY_ALLOW_UPDATE=1
"@ | Set-Content -Path $EnvFile -Encoding ASCII
Log "wrote $EnvFile"

# Run at boot as SYSTEM via a scheduled task (no service wrapper needed).
$action = "`"$Exe`" client --env-file `"$EnvFile`""
schtasks /Create /F /RU SYSTEM /SC ONSTART /RL HIGHEST /TN $TaskName /TR $action | Out-Null
schtasks /Run /TN $TaskName | Out-Null
Log "scheduled task '$TaskName' installed and started"
Log "done. The client should now appear as online in $AdminUrl"
Log "Logs: run '$Exe client --env-file `"$EnvFile`"' interactively to see output."
