#!/usr/bin/env bash
# SpawnRelay client installer for client "{{.ClientName}}"
# Generated by {{.AdminURL}} (server version {{.Version}})
#
# What this does:
#   1. downloads the spawnrelay binary for this machine from the relay server
#   2. writes /etc/spawnrelay/client.env with the tunnel address, token and
#      the relay's certificate fingerprint (pinned, so the tunnel cannot be
#      intercepted even though it uses a self-signed certificate)
#   3. installs and starts a systemd (Linux) or launchd (macOS) service
#
# The client accepts updates pushed from the relay's management interface
# (SPAWNRELAY_ALLOW_UPDATE=1 in client.env; set it to 0 to opt out). On Linux
# the binary therefore lives in the service's own state directory,
# /var/lib/spawnrelay-client, which the unprivileged service user can write.
set -euo pipefail

SERVER="{{.Server}}"
TOKEN="{{.Token}}"
FINGERPRINT="{{.Fingerprint}}"
ADMIN_URL="{{.AdminURL}}"
CURL_FLAGS="{{.CurlFlags}}"

CONF_DIR="${SPAWNRELAY_CONF_DIR:-/etc/spawnrelay}"
NO_SERVICE="${SPAWNRELAY_NO_SERVICE:-0}"
ALLOW_UPDATE="${SPAWNRELAY_ALLOW_UPDATE:-1}"
SVC_USER=spawnrelay

log() { printf '\033[1;36m[spawnrelay]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[spawnrelay] error:\033[0m %s\n' "$*" >&2; exit 1; }

if [ "$(id -u)" -ne 0 ]; then
  die "please run this installer as root, e.g. pipe it into 'sudo bash'"
fi

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$(uname -m)" in
  x86_64|amd64) arch="amd64" ;;
  aarch64|arm64) arch="arm64" ;;
  armv7l|armv6l) arch="arm" ;;
  i386|i686) arch="386" ;;
  *) die "unsupported architecture: $(uname -m)" ;;
esac
case "$os" in linux|darwin|freebsd) ;; *) die "unsupported operating system: $os" ;; esac

command -v curl >/dev/null 2>&1 || die "curl is required"

use_systemd=0
if [ "$os" = "linux" ] && [ "$NO_SERVICE" != "1" ] && command -v systemctl >/dev/null 2>&1; then
  use_systemd=1
fi
if [ -n "${SPAWNRELAY_BIN_DIR:-}" ]; then
  BIN_DIR="$SPAWNRELAY_BIN_DIR"
elif [ "$use_systemd" = "1" ]; then
  BIN_DIR=/var/lib/spawnrelay-client
else
  BIN_DIR=/usr/local/bin
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
log "downloading spawnrelay for ${os}/${arch} from ${ADMIN_URL}"
curl -fsSL ${CURL_FLAGS} "${ADMIN_URL}/dl/spawnrelay_${os}_${arch}" -o "$tmp" \
  || die "download failed. Ask the relay admin to add a ${os}/${arch} build to the server's bin directory."
chmod 0755 "$tmp"
mkdir -p "$BIN_DIR"
mv -f "$tmp" "${BIN_DIR}/spawnrelay"
trap - EXIT
log "installed ${BIN_DIR}/spawnrelay ($("${BIN_DIR}/spawnrelay" version 2>/dev/null || echo unknown))"
if [ "$use_systemd" = "1" ]; then
  if ! id "$SVC_USER" >/dev/null 2>&1; then
    useradd --system --home-dir "$BIN_DIR" --shell /usr/sbin/nologin "$SVC_USER"
  fi
  chown -R "$SVC_USER:$SVC_USER" "$BIN_DIR"
  chmod 0755 "$BIN_DIR"
  if [ "$BIN_DIR" != "/usr/local/bin" ] && [ -f /usr/local/bin/spawnrelay ]; then
    log "note: an older client binary remains at /usr/local/bin/spawnrelay; the service now runs ${BIN_DIR}/spawnrelay"
  fi
fi

mkdir -p "$CONF_DIR"
umask 077
cat >"${CONF_DIR}/client.env" <<ENV
# SpawnRelay client configuration (generated $(date -u +%Y-%m-%dT%H:%M:%SZ))
SPAWNRELAY_SERVER=${SERVER}
SPAWNRELAY_TOKEN=${TOKEN}
SPAWNRELAY_FINGERPRINT=${FINGERPRINT}
# Accept updates pushed from the relay's management interface (0 to refuse)
SPAWNRELAY_ALLOW_UPDATE=${ALLOW_UPDATE}
ENV
chmod 0600 "${CONF_DIR}/client.env"
log "wrote ${CONF_DIR}/client.env"

if [ "$NO_SERVICE" = "1" ]; then
  log "skipping service setup (SPAWNRELAY_NO_SERVICE=1). Run: ${BIN_DIR}/spawnrelay client --env-file ${CONF_DIR}/client.env"
  exit 0
fi

if [ "$use_systemd" = "1" ]; then
  cat >/etc/systemd/system/spawnrelay-client.service <<UNIT
[Unit]
Description=SpawnRelay client (tunnel to ${SERVER})
After=network-online.target
Wants=network-online.target

[Service]
# systemd reads the config as root before dropping privileges, so client.env
# can stay mode 0600. The binary lives in the state directory so the service
# can replace it when the relay pushes an update.
EnvironmentFile=${CONF_DIR}/client.env
ExecStart=${BIN_DIR}/spawnrelay client
Restart=always
RestartSec=3
User=${SVC_USER}
Group=${SVC_USER}
StateDirectory=spawnrelay-client
ReadWritePaths=${BIN_DIR}
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now spawnrelay-client.service
  sleep 1
  systemctl --no-pager --lines=5 status spawnrelay-client.service || true
  log "service installed. Logs: journalctl -u spawnrelay-client -f"
elif [ "$os" = "darwin" ]; then
  plist=/Library/LaunchDaemons/org.spawnrelay.client.plist
  cat >"$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>org.spawnrelay.client</string>
  <key>ProgramArguments</key><array>
    <string>${BIN_DIR}/spawnrelay</string><string>client</string>
    <string>--env-file</string><string>${CONF_DIR}/client.env</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>/var/log/spawnrelay-client.log</string>
  <key>StandardErrorPath</key><string>/var/log/spawnrelay-client.log</string>
</dict></plist>
PLIST
  launchctl bootout system "$plist" >/dev/null 2>&1 || true
  launchctl bootstrap system "$plist"
  log "launchd service installed. Logs: tail -f /var/log/spawnrelay-client.log"
else
  log "no service manager detected. Start the client with:"
  log "  ${BIN_DIR}/spawnrelay client --env-file ${CONF_DIR}/client.env"
fi

log "done. The client should now appear as online in ${ADMIN_URL}"
